spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/agro
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: false
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
server:
  servlet:
    context-path: /api
  compression:
    enabled: true
  port: 8585
tjf:
  api:
    filter:
      fields:
        enabled: true